- name: Prepare the system
  hosts: all
  become: true
  tasks:
    - name: Install the python3-debian package
      ansible.builtin.apt:
        name: python3-debian
        state: present
        update_cache: true
